import Pkg
Pkg.update()
Pkg.add("CSV")
Pkg.add("ColorBrewer")
Pkg.add("Colors")
Pkg.add("DSP")
Pkg.add("DataFrames")
Pkg.add("EEG")
Pkg.add("FileIO")
Pkg.add("Flux")
Pkg.add("GitHub")
Pkg.add("Gumbo")
Pkg.add("IJulia")
Pkg.add("ImageMagick")
Pkg.add("ImageView")
Pkg.add("Images")
Pkg.add("LaTeX")
Pkg.add("LaTeXStrings")
Pkg.add("LightGraphs")
Pkg.add("MAT")
Pkg.add("Plots")
Pkg.add("Pluto")
Pkg.add("PyCall")
Pkg.add("PyPlot")
# Pkg.add("PySide")
# Pkg.add("RCall")
# Pkg.add("RDatasets")
# Pkg.add("ScikitLearn")
# Pkg.add("ScikitLearnBase")
# Pkg.add("StatsBase")
# Pkg.add("StatsFuns")
Pkg.add("SymPy")
# Pkg.add("Taro")
# Pkg.add("TextAnalysis")
