apm install atom-beautify
apm install atom-css-comb
apm install autocomplete-python
apm install autoclose-html
apm install blame
apm install color-picker
apm install emmet
apm install figlet
apm install file-icons
apm install git-log
apm install git-plus
apm install hashrocket
apm install jekyll
apm install jslint
apm install language-latex
apm install language-prolog
apm install language-r
apm install language-vhdl
apm install linter
apm install linter-flake8
apm install merge-conflicts
apm install pigments
apm install python-tools
apm install set-syntax
apm install tidal
